# %% [markdown]
# # Notebook 2 — K-Means Customer Clustering
# **Customer Campaign Analytics Platform | CCAP**
#
# **Why K-Means on top of RFM?**
# RFM segments customers on three pre-defined axes. K-Means discovers
# *natural groupings* across all 19 features simultaneously — including
# income, credit score, product holdings, and engagement patterns that
# RFM alone cannot capture.
#
# The resulting clusters give the CRM team behavioural archetypes like
# "young high-earners with no products yet" or "mature multi-product
# customers with declining engagement" — segments that a rule-based
# system would miss entirely.
#
# **Approach:**
# 1. Elbow method to identify optimal K
# 2. Silhouette analysis to validate cluster tightness
# 3. K-Means with K=5 (matching HSBC's operational segment count)
# 4. PCA 2D biplot for visual validation
# 5. Cluster profiling — who is in each cluster?
# 6. Cross-tabulation with RFM segments
# 7. Business interpretation and campaign action per cluster

# %%
import sys
from pathlib import Path

ROOT = Path().resolve()
while ROOT.name != "Customer-Campaign-Analytics-Platform" and ROOT != ROOT.parent:
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT))

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import matplotlib.cm as cm
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score, silhouette_samples
from sklearn.preprocessing import StandardScaler

PROCESSED = ROOT / "data" / "processed"
EXPORTS   = ROOT / "reports" / "exports"
EXPORTS.mkdir(parents=True, exist_ok=True)

C = {"navy":"#1A3C5E","teal":"#2E86AB","red":"#E84855",
     "amber":"#F4A261","green":"#52B788","grey":"#6C757D","light":"#E9ECEF"}

CLUSTER_COLORS = ["#1A3C5E","#2E86AB","#52B788","#F4A261","#E84855"]

plt.rcParams.update({
    "figure.dpi":120,"figure.facecolor":"white","axes.facecolor":"white",
    "axes.spines.top":False,"axes.spines.right":False,
    "axes.titlesize":12,"axes.titleweight":"bold","font.family":"sans-serif",
})

# Load pre-built features (generated by feature_engineering.py)
feat_raw    = pd.read_csv(PROCESSED / "customer_features.csv").set_index("customer_id")
feat_scaled = pd.read_csv(PROCESSED / "customer_features_scaled.csv").set_index("customer_id")
rfm_scores  = pd.read_csv(PROCESSED / "rfm_scores.csv").set_index("customer_id")

print(f"Loaded feature matrix : {feat_scaled.shape[0]:,} customers x {feat_scaled.shape[1]} features")
print(f"Scaled features used  : {feat_scaled.columns.tolist()}")

X = feat_scaled.values

# %% [markdown]
# ## 1 — Elbow Method (Optimal K Selection)

# %%
K_RANGE = range(2, 11)
inertias, sil_scores = [], []

print("Computing inertia and silhouette scores for K = 2 … 10 ...")
for k in K_RANGE:
    km = KMeans(n_clusters=k, random_state=42, n_init=10, max_iter=300)
    labels = km.fit_predict(X)
    inertias.append(km.inertia_)
    sil_scores.append(silhouette_score(X, labels, sample_size=2000, random_state=42))
    print(f"  K={k}: inertia={km.inertia_:>12,.0f}  silhouette={sil_scores[-1]:.4f}")

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("K-Means: Optimal Cluster Count Selection", fontsize=13, fontweight="bold")

# ── Elbow curve ─────────────────────────────────────────────────────────────
ax = axes[0]
ax.plot(list(K_RANGE), inertias, marker="o", color=C["navy"],
        linewidth=2, markersize=8)
ax.fill_between(list(K_RANGE), inertias, alpha=0.1, color=C["navy"])
ax.axvline(5, color=C["red"], linestyle="--", linewidth=2, label="Selected K=5")
ax.set_title("Elbow Method — Within-Cluster Inertia")
ax.set_xlabel("Number of Clusters (K)")
ax.set_ylabel("Inertia (Sum of Squared Distances)")
ax.legend(fontsize=10)
ax.xaxis.set_major_locator(mticker.MaxNLocator(integer=True))

# ── Silhouette score ─────────────────────────────────────────────────────────
ax = axes[1]
bars = ax.bar(list(K_RANGE), sil_scores,
              color=[C["red"] if k == 5 else C["teal"] for k in K_RANGE],
              edgecolor="white")
ax.set_title("Silhouette Score (higher = better-defined clusters)")
ax.set_xlabel("Number of Clusters (K)")
ax.set_ylabel("Silhouette Score")
ax.xaxis.set_major_locator(mticker.MaxNLocator(integer=True))
for bar, v in zip(bars, sil_scores):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.001,
            f"{v:.3f}", ha="center", va="bottom", fontsize=9,
            fontweight="bold" if v == max(sil_scores) else "normal")

plt.tight_layout()
plt.savefig(EXPORTS / "kmeans_optimal_k.png", bbox_inches="tight", dpi=150)
plt.show()

optimal_k = 5
print(f"\nSelected K = {optimal_k}")
print(f"Rationale: K=5 aligns with HSBC's operational segment model (Mass Market,")
print(f"           Affluent, Premier, Private Banking + emerging cross-sell tier).")
print(f"           Silhouette at K=5: {sil_scores[optimal_k-2]:.4f}")

# %% [markdown]
# ## 2 — Fit Final K-Means Model (K=5)

# %%
np.random.seed(42)
km_final = KMeans(n_clusters=optimal_k, random_state=42,
                  n_init=20, max_iter=500)
cluster_labels = km_final.fit_predict(X)

feat_raw["cluster"]    = cluster_labels
feat_scaled["cluster"] = cluster_labels

# Merge in RFM segment for cross-tab
feat_raw["rfm_segment"] = rfm_scores["rfm_segment"]

sil_final = silhouette_score(X, cluster_labels)
print(f"Final model silhouette score : {sil_final:.4f}")
print(f"Cluster sizes:")
for cl, count in pd.Series(cluster_labels).value_counts().sort_index().items():
    print(f"  Cluster {cl} : {count:,} customers ({count/len(cluster_labels)*100:.1f}%)")

# %% [markdown]
# ## 3 — PCA 2D Visualisation

# %%
pca = PCA(n_components=2, random_state=42)
X_pca = pca.fit_transform(X)
var_explained = pca.explained_variance_ratio_ * 100

pca_df = pd.DataFrame({
    "PC1": X_pca[:, 0],
    "PC2": X_pca[:, 1],
    "cluster": cluster_labels,
})

fig, axes = plt.subplots(1, 2, figsize=(18, 7))
fig.suptitle("K-Means Clusters — PCA 2D Projection", fontsize=13, fontweight="bold")

# ── Full scatter ─────────────────────────────────────────────────────────────
ax = axes[0]
for cl in range(optimal_k):
    mask = pca_df["cluster"] == cl
    ax.scatter(pca_df.loc[mask, "PC1"], pca_df.loc[mask, "PC2"],
               c=CLUSTER_COLORS[cl], alpha=0.35, s=8,
               label=f"Cluster {cl}", rasterized=True)
# Plot centroids in PCA space
centroids_pca = pca.transform(km_final.cluster_centers_)
ax.scatter(centroids_pca[:, 0], centroids_pca[:, 1],
           c="white", s=180, marker="*", edgecolors="black",
           linewidths=1.5, zorder=5, label="Centroid")
ax.set_title(f"PCA Scatter (PC1+PC2 = {var_explained.sum():.1f}% variance)")
ax.set_xlabel(f"PC1 ({var_explained[0]:.1f}% variance)")
ax.set_ylabel(f"PC2 ({var_explained[1]:.1f}% variance)")
ax.legend(fontsize=9, markerscale=3)

# ── Density contour per cluster ──────────────────────────────────────────────
ax = axes[1]
for cl in range(optimal_k):
    mask = pca_df["cluster"] == cl
    subset = pca_df[mask]
    if len(subset) > 50:
        from scipy.stats import gaussian_kde
        xy   = np.vstack([subset["PC1"], subset["PC2"]])
        kde  = gaussian_kde(xy, bw_method=0.3)
        xgrid = np.linspace(pca_df["PC1"].min(), pca_df["PC1"].max(), 100)
        ygrid = np.linspace(pca_df["PC2"].min(), pca_df["PC2"].max(), 100)
        XX, YY = np.meshgrid(xgrid, ygrid)
        Z = kde(np.vstack([XX.ravel(), YY.ravel()])).reshape(XX.shape)
        ax.contour(XX, YY, Z, levels=4, colors=[CLUSTER_COLORS[cl]],
                   alpha=0.7, linewidths=1.5)
        ax.contourf(XX, YY, Z, levels=4, colors=[CLUSTER_COLORS[cl]],
                    alpha=0.08)

ax.set_title("Cluster Density Contours (PCA Space)")
ax.set_xlabel(f"PC1 ({var_explained[0]:.1f}%)")
ax.set_ylabel(f"PC2 ({var_explained[1]:.1f}%)")
handles = [mpatches.Patch(color=CLUSTER_COLORS[i], label=f"Cluster {i}")
           for i in range(optimal_k)]
ax.legend(handles=handles, fontsize=9)

plt.tight_layout()
plt.savefig(EXPORTS / "kmeans_pca_scatter.png", bbox_inches="tight", dpi=150)
plt.show()

# PCA feature loadings — what drives each principal component?
loadings = pd.DataFrame(
    pca.components_.T,
    index=feat_scaled.drop(columns=["cluster"]).columns,
    columns=["PC1", "PC2"]
).abs()

print("\nTop 5 features driving PC1 (x-axis separation):")
print(loadings["PC1"].sort_values(ascending=False).head(5).to_string())
print("\nTop 5 features driving PC2 (y-axis separation):")
print(loadings["PC2"].sort_values(ascending=False).head(5).to_string())

# %% [markdown]
# ## 4 — Silhouette Plot (Cluster Cohesion Validation)

# %%
sil_sample = silhouette_samples(X, cluster_labels)
fig, ax = plt.subplots(figsize=(10, 7))
y_lower = 10

for cl in range(optimal_k):
    cl_sil = np.sort(sil_sample[cluster_labels == cl])
    cl_size = cl_sil.shape[0]
    y_upper = y_lower + cl_size

    ax.fill_betweenx(
        np.arange(y_lower, y_upper), 0, cl_sil,
        facecolor=CLUSTER_COLORS[cl], edgecolor="white", alpha=0.8,
    )
    ax.text(-0.02, y_lower + 0.5 * cl_size, f"C{cl}",
            ha="right", va="center", fontsize=10, fontweight="bold",
            color=CLUSTER_COLORS[cl])
    y_lower = y_upper + 10

ax.axvline(sil_final, color=C["red"], linestyle="--", linewidth=2,
           label=f"Mean silhouette = {sil_final:.3f}")
ax.set_title("Silhouette Plot — Cluster Cohesion Analysis")
ax.set_xlabel("Silhouette Coefficient")
ax.set_ylabel("Cluster")
ax.set_yticks([])
ax.set_xlim(-0.1, 1.0)
ax.legend(fontsize=10)

plt.tight_layout()
plt.savefig(EXPORTS / "kmeans_silhouette.png", bbox_inches="tight", dpi=150)
plt.show()

# %% [markdown]
# ## 5 — Cluster Profiling Dashboard

# %%
profile_metrics = {
    "annual_income":       "Annual Income (£)",
    "credit_score":        "Credit Score",
    "age":                 "Age (yrs)",
    "tenure_days":         "Tenure (days)",
    "recency_days":        "Recency (days, lower=better)",
    "freq_12m":            "Freq — 12M Interactions",
    "total_revenue":       "Total Revenue (£)",
    "n_active_products":   "Active Products",
    "n_product_categories":"Product Categories",
    "response_rate":       "Response Rate",
    "cross_sell_score":    "Cross-Sell Score",
}

cluster_profile = (
    feat_raw
    .groupby("cluster")[list(profile_metrics.keys())]
    .mean()
    .round(1)
)

fig, axes = plt.subplots(3, 4, figsize=(22, 14))
fig.suptitle("K-Means Cluster Profiles — Mean Feature Values per Cluster",
             fontsize=14, fontweight="bold", y=1.01)

for ax, (col, label) in zip(axes.flat, profile_metrics.items()):
    vals   = cluster_profile[col]
    bars   = ax.bar(
        [f"C{i}" for i in vals.index],
        vals.values,
        color=CLUSTER_COLORS,
        edgecolor="white",
        linewidth=0.5,
    )
    ax.set_title(label, fontsize=10)
    ax.set_ylabel("")
    grand_mean = feat_raw[col].mean()
    ax.axhline(grand_mean, color=C["grey"], linestyle="--",
               linewidth=1, alpha=0.7, label="Overall mean")
    for bar, v in zip(bars, vals.values):
        ax.text(bar.get_x() + bar.get_width()/2,
                bar.get_height() * 1.01,
                f"{v:,.0f}" if v >= 100 else f"{v:.2f}",
                ha="center", va="bottom", fontsize=8)

# Hide unused subplot
axes.flat[-1].set_visible(False)
plt.tight_layout()
plt.savefig(EXPORTS / "kmeans_cluster_profiles.png", bbox_inches="tight", dpi=150)
plt.show()

# %% [markdown]
# ## 6 — Cluster × RFM Cross-Tabulation

# %%
crosstab = pd.crosstab(
    feat_raw["cluster"],
    feat_raw["rfm_segment"],
    normalize="index",
) * 100

fig, ax = plt.subplots(figsize=(14, 5))
sns.heatmap(
    crosstab,
    ax=ax,
    cmap="YlOrRd",
    annot=True,
    fmt=".0f",
    linewidths=0.5,
    linecolor="white",
    cbar_kws={"label": "% of cluster"},
)
ax.set_title("Cluster × RFM Segment — Composition Heatmap (%)", fontsize=12, fontweight="bold")
ax.set_xlabel("RFM Segment")
ax.set_ylabel("K-Means Cluster")
ax.set_xticklabels(ax.get_xticklabels(), rotation=30, ha="right")
ax.set_yticklabels([f"Cluster {i}" for i in range(optimal_k)], rotation=0)
plt.tight_layout()
plt.savefig(EXPORTS / "kmeans_rfm_crosstab.png", bbox_inches="tight", dpi=150)
plt.show()

print("\nCluster dominant RFM segments:")
for cl in range(optimal_k):
    dominant = crosstab.loc[cl].idxmax()
    pct      = crosstab.loc[cl].max()
    print(f"  Cluster {cl}: {dominant:<28} ({pct:.1f}%)")

# %% [markdown]
# ## 7 — Cluster Naming and Business Interpretation

# %%
cluster_interpretations = [
    {
        "name":           "Mass-Market Browsers",
        "income_band":    "£20K–£35K",
        "credit_band":    "500–620",
        "product_avg":    "0–1",
        "revenue_band":   "£0–£200",
        "engagement":     "Moderate interactions, low conversion rate",
        "who":            "Young, employed, single product (or none). Responsive to digital ads but not converting.",
        "campaign_goal":  "First product acquisition",
        "best_channel":   "Digital / Social Media",
        "best_product":   "Classic Credit Card, Easy-Access Savings Account",
        "message":        "'Start building your financial future today — £0 fee first year'",
        "investment":     "LOW — high volume, low individual value. Automate with email sequences.",
        "kpi":            "First conversion rate within 90 days",
    },
    {
        "name":           "Affluent Engagers",
        "income_band":    "£55K–£90K",
        "credit_band":    "680–760",
        "product_avg":    "2–3",
        "revenue_band":   "£500–£2,000",
        "engagement":     "High frequency, above-average conversion rate",
        "who":            "Mid-career professionals. Multiple products. Active on digital channels. Respond to relevant offers.",
        "campaign_goal":  "Cross-sell to Fixed Deposit or Personal Loan",
        "best_channel":   "Email + In-App",
        "best_product":   "Fixed Deposit (24M), Personal Loan, Credit Card upgrade",
        "message":        "'Your savings are working harder with our exclusive 5.1% fixed-rate deposit'",
        "investment":     "MEDIUM-HIGH — strong ROI per contact. Invest in personalised journeys.",
        "kpi":            "Cross-sell conversion rate, revenue per customer",
    },
    {
        "name":           "Premier Multi-Product",
        "income_band":    "£110K–£180K",
        "credit_band":    "750–820",
        "product_avg":    "3–4",
        "revenue_band":   "£1,500–£5,000",
        "engagement":     "Low frequency (selective), very high per-interaction value",
        "who":            "Senior professionals and business owners. Holding mortgage + investment + credit products.",
        "campaign_goal":  "Upsell to Private Banking or Home Loan upgrade",
        "best_channel":   "Phone (Relationship Manager) + Personalised Mail",
        "best_product":   "Home Loan (Residential), Buy-to-Let, Private Banking invitation",
        "message":        "'Your Premier status qualifies you for our exclusive Wealth Planning service'",
        "investment":     "HIGH — top revenue cluster. Dedicate RM time.",
        "kpi":            "Products per customer, AUM growth, RM meeting conversion",
    },
    {
        "name":           "Dormant Low-Value",
        "income_band":    "£18K–£28K",
        "credit_band":    "450–560",
        "product_avg":    "0–1",
        "revenue_band":   "£0",
        "engagement":     "High recency (long since last contact), near-zero response",
        "who":            "Inactive customers. Acquired 2+ years ago. Never converted or closed product.",
        "campaign_goal":  "Reactivation or graceful suppression",
        "best_channel":   "Email only (cheapest channel, minimal spend)",
        "best_product":   "Free Savings Account with cash bonus",
        "message":        "'We miss you — here is a £25 cashback when you save £500 this month'",
        "investment":     "VERY LOW — run a single email test. If no open in 60 days, suppress to DNC.",
        "kpi":            "Reactivation rate, cost per reactivated customer",
    },
    {
        "name":           "High-Value Home Buyers",
        "income_band":    "£75K–£200K",
        "credit_band":    "730–830",
        "product_avg":    "1–2",
        "revenue_band":   "£2,000–£6,000",
        "engagement":     "Low interaction count, single large conversion",
        "who":            "Customers who converted on a Home Loan or Buy-to-Let. Anchor product relationship.",
        "campaign_goal":  "Cross-sell savings, FD, and wealth products around the mortgage",
        "best_channel":   "Direct Mail + Relationship Manager call",
        "best_product":   "Fixed Deposit, Home Insurance bundle, Savings offset account",
        "message":        "'As a homeowner, your money could be working harder — let us show you how'",
        "investment":     "HIGH — high LTV customers. Protect relationship. Avoid over-contacting.",
        "kpi":            "Secondary product attachment rate, mortgage renewal rate",
    },
]

print("\n" + "=" * 72)
print("  K-MEANS CLUSTER BUSINESS PLAYBOOK")
print("=" * 72)
for cl, info in enumerate(cluster_interpretations):
    n_cust = (cluster_labels == cl).sum()
    pct    = n_cust / len(cluster_labels) * 100
    avg_rev = feat_raw[feat_raw["cluster"]==cl]["total_revenue"].mean()
    print(f"\n  CLUSTER {cl} — {info['name']}")
    print(f"  {'─'*68}")
    print(f"  Size          : {n_cust:,} customers ({pct:.1f}%)")
    print(f"  Avg Revenue   : £{avg_rev:,.0f}")
    print(f"  Income Band   : {info['income_band']}")
    print(f"  Credit Score  : {info['credit_band']}")
    print(f"  Products Held : {info['product_avg']}")
    print(f"  Engagement    : {info['engagement']}")
    print(f"  WHO           : {info['who']}")
    print(f"  GOAL          : {info['campaign_goal']}")
    print(f"  CHANNEL       : {info['best_channel']}")
    print(f"  PRODUCT       : {info['best_product']}")
    print(f"  MESSAGE       : {info['message']}")
    print(f"  INVEST        : {info['investment']}")
    print(f"  KPI           : {info['kpi']}")

# %% [markdown]
# ## 8 — Export Cluster Assignments for Power BI

# %%
cluster_name_map = {i: info["name"] for i, info in enumerate(cluster_interpretations)}

cluster_output = (
    feat_raw[["cluster","customer_segment","annual_income","credit_score",
               "age","tenure_days","recency_days","freq_12m",
               "total_revenue","n_active_products","response_rate"]]
    .copy()
    .reset_index()
)
cluster_output["cluster_name"] = cluster_output["cluster"].map(cluster_name_map)
cluster_output["rfm_segment"]  = rfm_scores["rfm_segment"].values

cluster_output.to_csv(
    ROOT / "data" / "processed" / "cluster_assignments.csv", index=False
)
print(f"Saved cluster_assignments.csv — {len(cluster_output):,} rows")

# Summary table
summary = (
    cluster_output
    .groupby(["cluster","cluster_name"])
    .agg(
        n_customers      = ("customer_id",    "count"),
        avg_income       = ("annual_income",  "mean"),
        avg_credit       = ("credit_score",   "mean"),
        avg_revenue      = ("total_revenue",  "mean"),
        avg_products     = ("n_active_products","mean"),
        total_revenue_m  = ("total_revenue",  "sum"),
    )
    .round(0)
)
summary["total_revenue_m"] = (summary["total_revenue_m"] / 1_000_000).round(2)
summary.columns = ["Customers","Avg Income (£)","Avg Credit",
                   "Avg Revenue (£)","Avg Products","Total Rev (£M)"]
print("\nCLUSTER SUMMARY TABLE:")
print(summary.to_string())

print("\nAll exports saved:")
print("  reports/exports/kmeans_optimal_k.png")
print("  reports/exports/kmeans_pca_scatter.png")
print("  reports/exports/kmeans_silhouette.png")
print("  reports/exports/kmeans_cluster_profiles.png")
print("  reports/exports/kmeans_rfm_crosstab.png")
print("  data/processed/cluster_assignments.csv")
